export const PRODUCT_REPOSITORY = 'PRODUCT_REPOSITORY'
export const DATA_SOURCE = 'DATA_SOURCE'
export const BLACKLIST_TOKEN_REPOSITORY ='BLACKLIST_TOKEN_REPOSITORY'
export const USER_REPOSITORY = 'USER_REPOSITORY'